### ISSUE TITLE
Blender Installation

### ISSUE THREAD

**Issue by EloideMarsac** [prochitecture/bpypolyskel#14]
I don't know if it's the correct place to ask this question , but after reading the documentation, I still don't understand how to use bpypolyskel in Blender.

**Comment by vvoovv** [comment]
Hi @EloideMarsac 

To try the demo in Blender download the bpypolyskel as a zip file and install a Blender addon.
Then
`Shift` `A` -> Add bpypolyskel Demo Object.

Take look at the code in the file &lowbar;&lowbar;init&lowbar;&lowbar;.py

**Comment by EloideMarsac** [comment]
Thanks for the answer. So if I want to use bpypolyskel in Blender on my own buildings footprint, I need to copy paste __init__.py in Blender's python console?

**Comment by vvoovv** [comment]
You will need to adapt the code in &lowbar;&lowbar;init&lowbar;&lowbar;.py to your needs. Please note that bpypolyskel is a general purpose Python library rather than a Blender addon.
