### ISSUE TITLE
Move to LGPL?

### ISSUE THREAD

**Issue by dwjp** [prochitecture/bpypolyskel#15]
Would it be possible to shift to the LGPL license which is what [polyskel](https://github.com/Botffy/polyskel) uses? 

bpypolyskel looks perfect for some analysis I'm doing on building outline data, but I'm unable to use it right now as it might be integrated into a commercial product down the track as an imported python package.

**Comment by vvoovv** [comment]
`bpypolyskel` was originally designed to be used within an addon for Blender. Both Blender and the addon are distributed under the GPL license. That's why we'd prefer to keep the GPL license.

Thank you for your understanding.

**Comment by dwjp** [comment]
Understood, didn't appreciate that the Blender integration meant you had to stick with GPL. 

polyskel will still be very useful, but was hoping to try out some of the improvements you made for hip roofs in particular. All the best with it.
