### ISSUE TITLE
Non-contiguous contours in the input parameter verts

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/bpypolyskel#7]
I've made a change in the signature of _polygonize(..)_ in the branch [holesInfo](https://github.com/prochitecture/bpypolyskel/tree/holesInfo).

Instead of _numVertsHoles_ the new paramater _holesInfo_ should be used.
It is _None_ if there are no holes or a Python list. In the latter case each element is a tuple that consists of the two elements:
1) The index of the first vertex of the hole in the input parameter _verts_
2) The number of vertices in the hole

**Comment by vvoovv** [comment]
The code between the lines [615-628](https://github.com/prochitecture/bpypolyskel/blob/holesInfo/bpypolyskel.py#L614) in _bpypolyskel.py_ (where the graph is formed) should be updated. I don't quite understand it.

**Comment by polarkernel** [comment]
> The code between the lines 615-628 in bpypolyskel.py (where the graph is formed) should be updated. I don't quite understand it.

The vertices of the sources and sinks of the skeleton are returned as 2D-coordinates by _skeletonize()_. In the mentioned code part, the indices of the sinks got searched in _edges2D_, under the assumption that the order of vertices in _verts_ corresponds to the order in _edges2D_. This is no more the case now and the search can no more be done in _edges2D_. It gets much more complicated now.

I will try to find a solution this evening.

**Comment by vvoovv** [comment]
A possible solution would be to store the indices of the related vertices in each instance of Edges2D.

**Comment by polarkernel** [comment]
> The code between the lines 615-628 in bpypolyskel.py ...

Update done. I adapted also the example _holey.py_ for my tests, but all other examples are not yet updated. Poorly tested, but should work.

**Comment by polarkernel** [comment]
> I've made a change in the signature of polygonize(..) in the branch holesInfo.

Will you merge this branch to master when you are happy with it?

**Comment by vvoovv** [comment]
Yes. I am making some tweaks to the code. Once it works, I'll merge to master

**Comment by vvoovv** [comment]
> Update done.

It worked for contiguous contours and didn't work for non-contiguous contours. The examples are attached.
[hole_symmetrical.py.txt](https://github.com/prochitecture/bpypolyskel/files/5405053/hole_symmetrical.py.txt)
[hole_symmetrical_noncontiguous.py.txt](https://github.com/prochitecture/bpypolyskel/files/5405055/hole_symmetrical_noncontiguous.py.txt)

I made some optimizations in the _holesInfo_ branch, basically removed extra Python lists, changed the class _Edge2_. But the problem persists.

I compared the graph indices in the line [633 ](https://github.com/prochitecture/bpypolyskel/blob/master/bpypolyskel.py#L633) for [hole_symmetrical.py.txt](https://github.com/prochitecture/bpypolyskel/files/5405053/hole_symmetrical.py.txt) and
[hole_symmetrical_noncontiguous.py.txt](https://github.com/prochitecture/bpypolyskel/files/5405055/hole_symmetrical_noncontiguous.py.txt). The indices point to the same coordinates of the polygon. It lookes like the graph doesn't like indices with breaks.

**Comment by polarkernel** [comment]
> It lookes like the graph doesn't like indices with breaks.

It does. The bug was in the call to _faces()_. At the very end of the function _faces()_ of _poly2FacesGraph_, one edge of the polygon or of a hole has to be rotated to the first position of the face edges. Additionally, the face of the polygon and the faces of the holes have to be removed from the result. To distinguish them from the skeleton edges, the first index of the skeleton _nrOfEdges+firstVertIndex_ had been used, which is no more correct for non-contiguous contours. Fixed now by usage of _firstSkelIndex_.

**Comment by vvoovv** [comment]
I removed a few more excessive Python lists in _polygonize(..)_ and merged the branch into the master.
